# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 64a358ad0369b7b004611c0de4e65d53d5e0cd02c5a1291a619785e9f94c825e58e20303941a68de4d1019e21365e90d0b801e1bad26d75d003698bdd4878990
  devise_pepper: ffca5b141494c1f8870c20a3edd8b80117d653c1f757f016ee71814d8d17622496106de88af286e07ce96a69be033295556832345b151ff22ec26a8f52d9dfcb

test:
  secret_key_base: 39907dd56a2f7d12ad4b6c250b5cda0257a0bdbb2b1496fd97612289b02bcc366e97f39fb6a8c0a4d2233da84a3a1667f93b06c56feb63a3e36840a1f573498c
  devise_pepper: ffca5b141494c1f8870c20a3edd8b80117d653c1f757f016ee71814d8d17622496106de88af286e07ce96a69be033295556832345b151ff22ec26a8f52d9dfcb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  devise_pepper: <%= ENV["DEVISE_PEPPER"] %>
